# Tên của workflow, sẽ hiển thị trên tab Actions của GitHub
name: Local CI/CD Deployment

# Kích hoạt workflow mỗi khi có push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Quan trọng: Chỉ định job này chạy trên runner bạn đã cài đặt
    runs-on: self-hosted

    steps:
      # Bước 1: Checkout code từ repository về runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Build Docker image từ Dockerfile
      - name: Build Docker image
        run: docker build -t mydotnetapp:latest .

      # Bước 3: Dừng container cũ nếu đang tồn tại
      - name: Stop existing container
        run: docker stop mydotnetapp-container || true
        continue-on-error: true

      # Bước 4: Xóa container cũ nếu đang tồn tại
      - name: Remove existing container
        run: docker rm mydotnetapp-container || true
        continue-on-error: true
      
      # Bước 5: Chạy container mới từ image vừa build
      # Ánh xạ cổng 8080 của máy bạn vào cổng 80 của container
      - name: Run new container
        run: docker run -d -p 8080:80 --name mydotnetapp-container mydotnetapp:latest 